### ISSUE TITLE
Duplicate papers in slack messages

### ISSUE THREAD

**Issue by rmorgan10** [abigailbishop/slackPoster#4]
The fix we tried to remove duplicated papers failed because it was internal to `lazy_astroph.py`, and since we run that script for each relevant category, the different runs don't talk to each other.

**Comment by rmorgan10** [comment]
A possible approach is to output a file listing the urls posted the first time `lazy_astroph.py` is run for a particular channel, then each subsequent time it is run the file could be read in and duplicate papers can be dropped before posting. Then the file would have to be updated during each subsequent run, so that the third or fourth category will not duplicate the second or third category.

Once `run_slackPoster.py` finishes all the categories for a channel, the file could be safely deleted, since the main param file will already keep track of where the script left off.

**Comment by abigailbishop** [comment]
Holy smokes I didn't see this comment.

I ended up doing the looping over arXiv channels within the `lazy_astroph.py` script. I created an array that `search_astroph` appends to after searching each arXiv channel. That master list is then fed through the rest of the script. We'll see if it works tonight or if it breaks anything! 

It required adjusting the format of some inputs so you might want to take a look at that. Non-urgent though.

**Comment by rmorgan10** [comment]
Oh I totally forgot I wrote that coment, I just didn't want to forget what I was thinking about at the time. I like your approach better because it doesn't rely on reading and writing to a bunch of files. Let's see what happens tonight!

**Comment by rmorgan10** [comment]
I've noticed something like this from watching the script run:
```
writing param_file plasma/.lazy_astroph-physics
ERROR: unable to open parameter file for writting
```
after each run and I think that might be what's causing this headache. The write permissions in that directory get really weird when running in a screen, so if out param file isn't successfully written then the script forgets where it last left off

**Comment by rmorgan10** [comment]
Turns out running the script through `nohup` instead of `screen` fixed the permission issues, and now duplicate papers are being properly removed
