### ISSUE TITLE
SlackPoster seems sad

### ISSUE THREAD

**Issue by rmorgan10** [abigailbishop/slackPoster#5]
The posts over the last couple days have been duplicates of old posts. Sometimes just a few papers, sometimes all of them. Idk what's going on. Goal for the week is to get our little friend back in tip-top shape.

**Comment by abigailbishop** [comment]
Aw poor lil dude.

**Comment by rmorgan10** [comment]
There's like a 30% chance this commit [535730b](https://github.com/abigailbishop/slackPoster/commit/535730b603f7f9641193e68a831f092428128263) fixed the problem. The param file wasn't being written, which caused the old papers to continue to be posted. It's a little weird to me that the 'w' option wasn't enough since the old param file already existed, but switching to 'w+' seemed to fix it when I tested on the astro channel.

Sunday will still post duplicate papers since the param files need to be updated, but Monday hopefully we'll see if this fix worked.

**Comment by rmorgan10** [comment]
Lil dude is doing amazing now
